### ISSUE TITLE
is it possible to use github user pages?

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/gh-pages-template#2]
as evidenced by https://github.com/mojombo/mojombo.github.com/blob/master/CNAME you can use a CNAME file with User/Org pages (more info [here](https://help.github.com/articles/user-organization-and-project-pages))

cc @briandoll

what I'm wondering is the existence of a User/Org page (which will take user.github.com and point it to the master branch of some repo) blocks other repos that you have from getting user.github.com/myreponame urls? can you both at once?

**Comment by briandoll** [comment]
It is possible. I'm not sure why that project page didn't render under my account.. it triggered a 404 that was caught by my user pages repo (which I should probably delete anyway)

An example of this working:
- [Twitter's organization page](http://twitter.github.com/)
- [Finagle project pages under their org](http://twitter.github.com/finagle/)
- [gh-pages branch on finagle](https://github.com/twitter/finagle/tree/gh-pages)

**Comment by max-mapper** [comment]
Gotcha. I also found out you have to make one commit on the fork before it renders. Edited the readme just now to reflect this
